import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    header: {
        padding: 24,
        paddingTop: 20,
        backgroundColor: 'white',
        borderBottomWidth: 1,
        borderColor: '#E2E8F0',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
    },
    stats: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    statCard: {
        flex: 1,
        backgroundColor: '#F1F5F9',
        padding: 12,
        borderRadius: 12,
        marginHorizontal: 4,
        alignItems: 'center',
    },
    statLabel: {
        fontSize: 10,
        color: '#64748B',
        fontWeight: '800',
        textTransform: 'uppercase',
        marginBottom: 4,
    },
    statValue: {
        fontSize: 18,
        fontWeight: '800',
        color: '#1E293B',
    },
    actionRow: {
        flexDirection: 'row',
        gap: 12,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: '#F1F5F9',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    actionText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#475569',
        marginLeft: 6,
    },
    statusIndicator: {
        marginTop: 16,
        padding: 8,
        borderRadius: 8,
        alignItems: 'center',
    },
    statusIndicatorText: {
        color: 'white',
        fontWeight: '800',
        fontSize: 11,
        letterSpacing: 1,
    },
    list: {
        padding: 16,
    },
    itemCard: {
        backgroundColor: 'white',
        padding: 16,
        borderRadius: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 5,
        elevation: 1,
    },
    itemInfo: {
        flex: 1,
    },
    itemCode: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1E293B',
        marginBottom: 2,
    },
    itemDate: {
        fontSize: 11,
        color: '#94A3B8',
    },
    quantityContainer: {
        backgroundColor: '#EEF2FF',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        alignItems: 'center',
        marginRight: 12,
    },
    quantityValue: {
        fontSize: 18,
        fontWeight: '800',
        color: '#4F46E5',
    },
    quantityLabel: {
        fontSize: 9,
        color: '#4F46E5',
        fontWeight: '700',
    },
    deleteButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#FEF2F2',
        alignItems: 'center',
        justifyContent: 'center',
    },
    scanButton: {
        position: 'absolute',
        bottom: 40,
        left: 24,
        right: 24,
        backgroundColor: '#4F46E5',
        paddingVertical: 22,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#4F46E5',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    },
    scanButtonText: {
        color: 'white',
        fontSize: 20,
        fontWeight: '900',
        letterSpacing: 1,
        marginLeft: 12,
    },
    emptyState: {
        alignItems: 'center',
        marginTop: 60,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#475569',
        marginTop: 16,
    },
    emptySubText: {
        color: '#94A3B8',
        marginTop: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.7)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: 40,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1E293B',
        marginBottom: 24,
        textAlign: 'center',
    },
    input: {
        backgroundColor: '#F1F5F9',
        borderRadius: 16,
        padding: 16,
        fontSize: 24,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 24,
        color: '#1E293B',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        padding: 16,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButton: {
        backgroundColor: '#F1F5F9',
    },
    confirmButton: {
        backgroundColor: '#4F46E5',
    },
    buttonText: {
        fontWeight: '700',
        fontSize: 16,
    },
});
